# - hosts: localhost
#   connection: local
#   tasks:
#     - name: Copy custom index.html
#       command: docker cp files/index.html frontend:/usr/share/nginx/html/index.html

- hosts: localhost
  connection: local
  tasks:
    - name: Copy custom index.html
      shell: docker cp {{ playbook_dir }}/../../files/index.html frontend:/usr/share/nginx/html/index.html


